name: Docusaurus site CI

on:
  push:
    branches: [ master, upgrade ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: echo 'gpt-analytics.gpt-partners.com' > ./build/CNAME 
    - run: pwd
    - run: ls
    - run: ls build
    - run: git subtree push --prefix build origin gh-pages
