name: Docusaurus site CI

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/configure-pages@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: echo 'gpt-analytics.gpt-partners.com' > ./build/CNAME 
    - uses: actions/upload-pages-artifact@v1
      with:
        path: 'build'
    - uses: actions/deploy-pages@v2
